"use client"

import { useEffect, useState, useCallback } from "react"
import { useParams, useRouter } from "next/navigation"
import { ThreePaneLayout } from "@/components/layout"
import { LessonWorkspace } from "@/components/lesson"
import { ChatContainer } from "@/components/chat"
import { Button } from "@/components/ui/button"
import { ArrowLeft, Loader2 } from "lucide-react"
import Link from "next/link"
import type { LessonUIState, LessonBlock } from "@/lib/schemas"
import { createEmptyLessonUIState } from "@/lib/schemas"
import { UIPlanner } from "@/lib/planner"

interface Lesson {
  id: string
  title: string
  ui_schema: LessonUIState
  chats?: { messages: unknown[] }
}

export default function LessonPage() {
  const params = useParams()
  const router = useRouter()
  const lessonId = params.id as string

  const [lesson, setLesson] = useState<Lesson | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [planner, setPlanner] = useState<UIPlanner | null>(null)
  const [uiState, setUiState] = useState<LessonUIState | null>(null)

  // Fetch lesson data
  useEffect(() => {
    async function fetchLesson() {
      try {
        const res = await fetch(`/api/lessons/${lessonId}`)
        if (!res.ok) {
          if (res.status === 401) {
            router.push("/login")
            return
          }
          throw new Error("Failed to load lesson")
        }
        const data = await res.json()
        setLesson(data)

        // Initialize planner with lesson UI state
        const initialState = data.ui_schema || createEmptyLessonUIState(lessonId)
        const newPlanner = new UIPlanner(initialState)
        setPlanner(newPlanner)
        setUiState(newPlanner.getState())
      } catch (err) {
        setError(err instanceof Error ? err.message : "Unknown error")
      } finally {
        setLoading(false)
      }
    }

    fetchLesson()
  }, [lessonId, router])

  // Handle blocks generated by AI
  const handleBlocksGenerated = useCallback((blocks: LessonBlock[]) => {
    if (!planner) return

    for (const block of blocks) {
      planner.addBlockDirect(block)
    }

    const newState = planner.getState()
    setUiState(newState)

    // Persist to backend
    fetch(`/api/lessons/${lessonId}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ ui_schema: newState })
    })
  }, [planner, lessonId])

  // Handle UI state changes from workspace
  const handleStateChange = useCallback((newState: LessonUIState) => {
    setUiState(newState)

    // Persist to backend
    fetch(`/api/lessons/${lessonId}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ ui_schema: newState })
    })
  }, [lessonId])

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    )
  }

  if (error || !lesson || !uiState) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <p className="text-destructive mb-4">{error || "Lesson not found"}</p>
          <Link href="/lessons">
            <Button variant="outline">
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back to Lessons
            </Button>
          </Link>
        </div>
      </div>
    )
  }

  return (
    <ThreePaneLayout
      leftPane={
        <div className="p-4">
          <Link href="/lessons">
            <Button variant="ghost" size="sm" className="mb-4">
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back
            </Button>
          </Link>
          <h2 className="font-semibold text-lg mb-2">{lesson.title}</h2>
          <p className="text-sm text-muted-foreground">
            Lesson workspace
          </p>
        </div>
      }
      centerPane={
        <LessonWorkspace
          lessonId={lessonId}
          initialState={uiState}
          onStateChange={handleStateChange}
        />
      }
      rightPane={
        <ChatContainer
          lessonId={lessonId}
          onBlocksGenerated={handleBlocksGenerated}
        />
      }
    />
  )
}
